[package]
name = "ardent"
version = "0.13.0"
description = "An opinionated code formatter for NSIS scripts"
authors = ["Jan T. Sott"]
repository = "https://github.com/idleberg/ardent"
license = "MIT"
edition = "2024"
readme = "README.md"
documentation = "https://docs.rs/ardent"
homepage = "https://idleberg.github.io/ardent"
keywords = ["nsis", "formatter", "linter"]
categories = ["command-line-utilities", "development-tools"]
include = ["src", "README.md"]

[lib]
name = "ardent"
path = "src/lib.rs"

[[bin]]
name = "ardent"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
glob = "0.3"
peg = "0.8"
similar = "3.1.1"

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = true
strip = true
