//! Canonical casing lookup tables for NSIS instruction parameters.
//!
//! Generated from the Dent Style Specification 0.1.0 by `mise run spec:codegen`.
//! Do not edit — change the spec instead.

use std::collections::HashMap;
use std::sync::LazyLock;

/// Maps lowercased global parameters (e.g. `/silent`) to their canonical casing.
pub static GLOBAL_PARAMETERS: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
	HashMap::from([
		("/a", "/a"),
		("/bom", "/BOM"),
		("/branding", "/BRANDING"),
		("/componentsonlyoncustom", "/COMPONENTSONLYONCUSTOM"),
		("/date", "/date"),
		("/e", "/e"),
		("/enablecancel", "/ENABLECANCEL"),
		("/exeresource", "/EXERESOURCE"),
		("/file", "/file"),
		("/fileexists", "/FILEEXISTS"),
		("/filesonly", "/FILESONLY"),
		("/final", "/FINAL"),
		("/global", "/GLOBAL"),
		("/ifempty", "/ifempty"),
		("/ifndef", "/ifndef"),
		("/ifnosubkeys", "/ifnosubkeys"),
		("/ifnovalues", "/ifnovalues"),
		("/ignorecase", "/ignorecase"),
		("/intfmt", "/intfmt"),
		("/italic", "/ITALIC"),
		("/math", "/math"),
		("/nocustom", "/NOCUSTOM"),
		("/noerrors", "/NOERRORS"),
		("/nonfatal", "/NONFATAL"),
		("/nounload", "/nounload"),
		("/noworkingdir", "/NoWorkingDir"),
		("/o", "/o"),
		("/overwrite", "/OVERWRITE"),
		("/packed", "/packed"),
		("/plugin", "/plugin"),
		("/productversion", "/ProductVersion"),
		("/r", "/r"),
		("/rawnl", "/RAWNL"),
		("/rebootok", "/REBOOTOK"),
		("/redef", "/redef"),
		("/regedit5", "/REGEDIT5"),
		("/replace", "/REPLACE"),
		("/resizetofit", "/RESIZETOFIT"),
		("/resizetofitheight", "/RESIZETOFITHEIGHT"),
		("/resizetofitwidth", "/RESIZETOFITWIDTH"),
		("/sd", "/SD"),
		("/short", "/SHORT"),
		("/silent", "/SILENT"),
		("/solid", "/SOLID"),
		("/strike", "/STRIKE"),
		("/stringid", "/STRINGID"),
		("/target", "/target"),
		("/trimcenter", "/TRIMCENTER"),
		("/trimleft", "/TRIMLEFT"),
		("/trimright", "/TRIMRIGHT"),
		("/underline", "/UNDERLINE"),
		(
			"/uninstcomponentsonlyoncustom",
			"/UNINSTCOMPONENTSONLYONCUSTOM",
		),
		("/uninstnocustom", "/UNINSTNOCUSTOM"),
		("/utcdate", "/utcdate"),
		("/windows", "/windows"),
		("/x", "/x"),
	])
});

/// Maps lowercased parameter prefixes (e.g. `/timeout=`) to their canonical casing.
pub static GLOBAL_PARAMETER_PREFIXES: LazyLock<HashMap<&'static str, &'static str>> =
	LazyLock::new(|| {
		HashMap::from([
			("/charset=", "/CHARSET="),
			("/customstring=", "/CUSTOMSTRING="),
			("/imgid=", "/IMGID="),
			("/lang=", "/LANG="),
			("/oname=", "/oname="),
			("/timeout=", "/TIMEOUT="),
			("/uninstcustomstring=", "/UNINSTCUSTOMSTRING="),
		])
	});

/// Maps lowercased instruction names to the canonical casing of their parameters.
pub static INSTRUCTION_PARAMETERS: LazyLock<
	HashMap<&'static str, HashMap<&'static str, &'static str>>,
> = LazyLock::new(|| {
	HashMap::from([
		(
			"addbrandingimage",
			HashMap::from([
				("bottom", "bottom"),
				("left", "left"),
				("right", "right"),
				("top", "top"),
			]),
		),
		(
			"allowrootdirinstall",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"allowskipfiles",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"autoclosewindow",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		("changeui", HashMap::from([("dlg_id", "dlg_id")])),
		(
			"crccheck",
			HashMap::from([
				("false", "false"),
				("off", "off"),
				("on", "on"),
				("true", "true"),
			]),
		),
		(
			"createshortcut",
			HashMap::from([
				("alt", "ALT"),
				("control", "CONTROL"),
				("ext", "EXT"),
				("shift", "SHIFT"),
				("sw_hide", "SW_HIDE"),
				("sw_show", "SW_SHOW"),
				("sw_showmaximized", "SW_SHOWMAXIMIZED"),
				("sw_showminimized", "SW_SHOWMINIMIZED"),
				("sw_shownormal", "SW_SHOWNORMAL"),
			]),
		),
		(
			"deleteregkey",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"deleteregvalue",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"dirshow",
			HashMap::from([("hide", "hide"), ("show", "show")]),
		),
		(
			"dirverify",
			HashMap::from([("auto", "auto"), ("leave", "leave")]),
		),
		(
			"enumregkey",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"enumregvalue",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"execshell",
			HashMap::from([("open", "open"), ("print", "print")]),
		),
		(
			"execshellwait",
			HashMap::from([("open", "open"), ("print", "print")]),
		),
		(
			"fileopen",
			HashMap::from([("a", "a"), ("r", "r"), ("w", "w")]),
		),
		(
			"fileseek",
			HashMap::from([("cur", "CUR"), ("end", "END"), ("set", "SET")]),
		),
		(
			"getwinver",
			HashMap::from([
				("build", "BUILD"),
				("major", "MAJOR"),
				("minor", "MINOR"),
				("servicepack", "SERVICEPACK"),
			]),
		),
		(
			"installdirregkey",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"instprogressflags",
			HashMap::from([("colored", "colored"), ("smooth", "smooth")]),
		),
		(
			"licenseforceselection",
			HashMap::from([
				("checkbox", "checkbox"),
				("off", "off"),
				("on", "on"),
				("radiobuttons", "radiobuttons"),
			]),
		),
		("lockwindow", HashMap::from([("off", "off"), ("on", "on")])),
		("logset", HashMap::from([("off", "off"), ("on", "on")])),
		(
			"manifestdisablewindowfiltering",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"manifestdpiaware",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"manifestgdiscaling",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"manifestlongpathaware",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"manifestsupportedos",
			HashMap::from([
				("win10", "Win10"),
				("win7", "Win7"),
				("win8", "Win8"),
				("win8.1", "Win8.1"),
				("winvista", "WinVista"),
			]),
		),
		(
			"messagebox",
			HashMap::from([
				("idabort", "IDABORT"),
				("idcancel", "IDCANCEL"),
				("idignore", "IDIGNORE"),
				("idno", "IDNO"),
				("idok", "IDOK"),
				("idretry", "IDRETRY"),
				("idyes", "IDYES"),
				("mb_abortretryignore", "MB_ABORTRETRYIGNORE"),
				("mb_defbutton1", "MB_DEFBUTTON1"),
				("mb_defbutton2", "MB_DEFBUTTON2"),
				("mb_defbutton3", "MB_DEFBUTTON3"),
				("mb_defbutton4", "MB_DEFBUTTON4"),
				("mb_iconexclamation", "MB_ICONEXCLAMATION"),
				("mb_iconinformation", "MB_ICONINFORMATION"),
				("mb_iconquestion", "MB_ICONQUESTION"),
				("mb_iconstop", "MB_ICONSTOP"),
				("mb_ok", "MB_OK"),
				("mb_okcancel", "MB_OKCANCEL"),
				("mb_retrycancel", "MB_RETRYCANCEL"),
				("mb_right", "MB_RIGHT"),
				("mb_setforeground", "MB_SETFOREGROUND"),
				("mb_topmost", "MB_TOPMOST"),
				("mb_usericon", "MB_USERICON"),
				("mb_yesno", "MB_YESNO"),
				("mb_yesnocancel", "MB_YESNOCANCEL"),
			]),
		),
		(
			"page",
			HashMap::from([
				("components", "components"),
				("custom", "custom"),
				("directory", "directory"),
				("instfiles", "instfiles"),
				("license", "license"),
				("uninstconfirm", "uninstConfirm"),
			]),
		),
		(
			"readregdword",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"readregstr",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"requestexecutionlevel",
			HashMap::from([
				("admin", "admin"),
				("highest", "highest"),
				("none", "none"),
				("user", "user"),
			]),
		),
		(
			"setautoclose",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"setcompress",
			HashMap::from([
				("auto", "auto"),
				("force", "force"),
				("off", "off"),
				("on", "on"),
			]),
		),
		(
			"setcompressor",
			HashMap::from([("bzip2", "bzip2"), ("lzma", "lzma"), ("zlib", "zlib")]),
		),
		(
			"setctlcolors",
			HashMap::from([("transparent", "transparent")]),
		),
		(
			"setdatablockoptimize",
			HashMap::from([
				("false", "false"),
				("off", "off"),
				("on", "on"),
				("true", "true"),
			]),
		),
		(
			"setdatesave",
			HashMap::from([
				("false", "false"),
				("off", "off"),
				("on", "on"),
				("true", "true"),
			]),
		),
		(
			"setdetailsprint",
			HashMap::from([
				("both", "both"),
				("lastused", "lastused"),
				("listonly", "listonly"),
				("none", "none"),
				("textonly", "textonly"),
			]),
		),
		(
			"setdetailsview",
			HashMap::from([("hide", "hide"), ("show", "show")]),
		),
		(
			"setfileattributes",
			HashMap::from([
				("archive", "ARCHIVE"),
				("hidden", "HIDDEN"),
				("offline", "OFFLINE"),
				("readonly", "READONLY"),
				("system", "SYSTEM"),
				("temporary", "TEMPORARY"),
			]),
		),
		(
			"setoverwrite",
			HashMap::from([
				("ifdiff", "ifdiff"),
				("ifnewer", "ifnewer"),
				("lastused", "lastused"),
				("off", "off"),
				("on", "on"),
				("try", "try"),
			]),
		),
		(
			"setpluginunload",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		("setregview", HashMap::from([("default", "default")])),
		(
			"setshellvarcontext",
			HashMap::from([("all", "all"), ("current", "current")]),
		),
		(
			"setsilent",
			HashMap::from([("normal", "normal"), ("silent", "silent")]),
		),
		(
			"showinstdetails",
			HashMap::from([
				("hide", "hide"),
				("nevershow", "nevershow"),
				("show", "show"),
			]),
		),
		(
			"showuninstdetails",
			HashMap::from([
				("hide", "hide"),
				("nevershow", "nevershow"),
				("show", "show"),
			]),
		),
		(
			"showwindow",
			HashMap::from([
				("sw_hide", "SW_HIDE"),
				("sw_show", "SW_SHOW"),
				("sw_showmaximized", "SW_SHOWMAXIMIZED"),
				("sw_showminimized", "SW_SHOWMINIMIZED"),
				("sw_shownormal", "SW_SHOWNORMAL"),
			]),
		),
		(
			"silentinstall",
			HashMap::from([
				("normal", "normal"),
				("silent", "silent"),
				("silentlog", "silentlog"),
			]),
		),
		(
			"silentuninstall",
			HashMap::from([("normal", "normal"), ("silent", "silent")]),
		),
		(
			"target",
			HashMap::from([("amd64", "amd64"), ("x86", "x86")]),
		),
		(
			"unicode",
			HashMap::from([("false", "false"), ("true", "true")]),
		),
		(
			"uninstpage",
			HashMap::from([
				("components", "components"),
				("custom", "custom"),
				("directory", "directory"),
				("instfiles", "instfiles"),
				("license", "license"),
				("uninstconfirm", "uninstConfirm"),
			]),
		),
		(
			"windowicon",
			HashMap::from([
				("false", "false"),
				("off", "off"),
				("on", "on"),
				("true", "true"),
			]),
		),
		(
			"writeregbin",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"writeregdword",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"writeregexpandstr",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"writeregmultistr",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"writeregnone",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		(
			"writeregstr",
			HashMap::from([
				("hkcc", "HKCC"),
				("hkcr", "HKCR"),
				("hkcr32", "HKCR32"),
				("hkcr64", "HKCR64"),
				("hkcu", "HKCU"),
				("hkcu32", "HKCU32"),
				("hkcu64", "HKCU64"),
				("hkdd", "HKDD"),
				("hklm", "HKLM"),
				("hklm32", "HKLM32"),
				("hklm64", "HKLM64"),
				("hkpd", "HKPD"),
				("hku", "HKU"),
				("shctx", "SHCTX"),
			]),
		),
		("xpstyle", HashMap::from([("off", "off"), ("on", "on")])),
	])
});
